/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.proto;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Fridgeinfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Fridgeinfo\",\"namespace\":\"avro.proto\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Fridgeinfo() {}

  /**
   * All-args constructor.
   */
  public Fridgeinfo(java.lang.Integer id) {
    this.id = id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /** Creates a new Fridgeinfo RecordBuilder */
  public static avro.proto.Fridgeinfo.Builder newBuilder() {
    return new avro.proto.Fridgeinfo.Builder();
  }
  
  /** Creates a new Fridgeinfo RecordBuilder by copying an existing Builder */
  public static avro.proto.Fridgeinfo.Builder newBuilder(avro.proto.Fridgeinfo.Builder other) {
    return new avro.proto.Fridgeinfo.Builder(other);
  }
  
  /** Creates a new Fridgeinfo RecordBuilder by copying an existing Fridgeinfo instance */
  public static avro.proto.Fridgeinfo.Builder newBuilder(avro.proto.Fridgeinfo other) {
    return new avro.proto.Fridgeinfo.Builder(other);
  }
  
  /**
   * RecordBuilder for Fridgeinfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Fridgeinfo>
    implements org.apache.avro.data.RecordBuilder<Fridgeinfo> {

    private int id;

    /** Creates a new Builder */
    private Builder() {
      super(avro.proto.Fridgeinfo.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.proto.Fridgeinfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Fridgeinfo instance */
    private Builder(avro.proto.Fridgeinfo other) {
            super(avro.proto.Fridgeinfo.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public avro.proto.Fridgeinfo.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public avro.proto.Fridgeinfo.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Fridgeinfo build() {
      try {
        Fridgeinfo record = new Fridgeinfo();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
