/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.proto;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface getlights {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"getlights\",\"namespace\":\"avro.proto\",\"types\":[],\"messages\":{\"getlights\":{\"request\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"status\",\"type\":\"boolean\"}],\"response\":\"int\"}}}");
  int getlights(int id, boolean status) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends getlights {
    public static final org.apache.avro.Protocol PROTOCOL = avro.proto.getlights.PROTOCOL;
    void getlights(int id, boolean status, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
  }
}