/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.proto;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Hello {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Hello\",\"namespace\":\"avro.proto\",\"types\":[],\"messages\":{\"connect\":{\"request\":[],\"response\":\"int\"}}}");
  int connect() throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends Hello {
    public static final org.apache.avro.Protocol PROTOCOL = avro.proto.Hello.PROTOCOL;
    void connect(org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
  }
}