/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.proto;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Lightinfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Lightinfo\",\"namespace\":\"avro.proto\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"status\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int id;
  @Deprecated public boolean status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Lightinfo() {}

  /**
   * All-args constructor.
   */
  public Lightinfo(java.lang.Integer id, java.lang.Boolean status) {
    this.id = id;
    this.status = status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: status = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'status' field.
   */
  public java.lang.Boolean getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.Boolean value) {
    this.status = value;
  }

  /** Creates a new Lightinfo RecordBuilder */
  public static avro.proto.Lightinfo.Builder newBuilder() {
    return new avro.proto.Lightinfo.Builder();
  }
  
  /** Creates a new Lightinfo RecordBuilder by copying an existing Builder */
  public static avro.proto.Lightinfo.Builder newBuilder(avro.proto.Lightinfo.Builder other) {
    return new avro.proto.Lightinfo.Builder(other);
  }
  
  /** Creates a new Lightinfo RecordBuilder by copying an existing Lightinfo instance */
  public static avro.proto.Lightinfo.Builder newBuilder(avro.proto.Lightinfo other) {
    return new avro.proto.Lightinfo.Builder(other);
  }
  
  /**
   * RecordBuilder for Lightinfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Lightinfo>
    implements org.apache.avro.data.RecordBuilder<Lightinfo> {

    private int id;
    private boolean status;

    /** Creates a new Builder */
    private Builder() {
      super(avro.proto.Lightinfo.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.proto.Lightinfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Lightinfo instance */
    private Builder(avro.proto.Lightinfo other) {
            super(avro.proto.Lightinfo.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public avro.proto.Lightinfo.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public avro.proto.Lightinfo.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'status' field */
    public java.lang.Boolean getStatus() {
      return status;
    }
    
    /** Sets the value of the 'status' field */
    public avro.proto.Lightinfo.Builder setStatus(boolean value) {
      validate(fields()[1], value);
      this.status = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'status' field has been set */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'status' field */
    public avro.proto.Lightinfo.Builder clearStatus() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Lightinfo build() {
      try {
        Lightinfo record = new Lightinfo();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.status = fieldSetFlags()[1] ? this.status : (java.lang.Boolean) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
