/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.proto;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface sysserver {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"sysserver\",\"namespace\":\"avro.proto\",\"types\":[],\"messages\":{\"connect\":{\"request\":[{\"name\":\"type2\",\"type\":\"string\"}],\"response\":\"int\"},\"getlights\":{\"request\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"status\",\"type\":\"boolean\"}],\"response\":\"int\"}}}");
  int connect(java.lang.CharSequence type2) throws org.apache.avro.AvroRemoteException;
  int getlights(int id, boolean status) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends sysserver {
    public static final org.apache.avro.Protocol PROTOCOL = avro.proto.sysserver.PROTOCOL;
    void connect(java.lang.CharSequence type2, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void getlights(int id, boolean status, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
  }
}