/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.proto;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TSinfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TSinfo\",\"namespace\":\"avro.proto\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"measurement\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int id;
  @Deprecated public double measurement;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public TSinfo() {}

  /**
   * All-args constructor.
   */
  public TSinfo(java.lang.Integer id, java.lang.Double measurement) {
    this.id = id;
    this.measurement = measurement;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return measurement;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: measurement = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'measurement' field.
   */
  public java.lang.Double getMeasurement() {
    return measurement;
  }

  /**
   * Sets the value of the 'measurement' field.
   * @param value the value to set.
   */
  public void setMeasurement(java.lang.Double value) {
    this.measurement = value;
  }

  /** Creates a new TSinfo RecordBuilder */
  public static avro.proto.TSinfo.Builder newBuilder() {
    return new avro.proto.TSinfo.Builder();
  }
  
  /** Creates a new TSinfo RecordBuilder by copying an existing Builder */
  public static avro.proto.TSinfo.Builder newBuilder(avro.proto.TSinfo.Builder other) {
    return new avro.proto.TSinfo.Builder(other);
  }
  
  /** Creates a new TSinfo RecordBuilder by copying an existing TSinfo instance */
  public static avro.proto.TSinfo.Builder newBuilder(avro.proto.TSinfo other) {
    return new avro.proto.TSinfo.Builder(other);
  }
  
  /**
   * RecordBuilder for TSinfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TSinfo>
    implements org.apache.avro.data.RecordBuilder<TSinfo> {

    private int id;
    private double measurement;

    /** Creates a new Builder */
    private Builder() {
      super(avro.proto.TSinfo.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.proto.TSinfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.measurement)) {
        this.measurement = data().deepCopy(fields()[1].schema(), other.measurement);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing TSinfo instance */
    private Builder(avro.proto.TSinfo other) {
            super(avro.proto.TSinfo.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.measurement)) {
        this.measurement = data().deepCopy(fields()[1].schema(), other.measurement);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public avro.proto.TSinfo.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public avro.proto.TSinfo.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'measurement' field */
    public java.lang.Double getMeasurement() {
      return measurement;
    }
    
    /** Sets the value of the 'measurement' field */
    public avro.proto.TSinfo.Builder setMeasurement(double value) {
      validate(fields()[1], value);
      this.measurement = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'measurement' field has been set */
    public boolean hasMeasurement() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'measurement' field */
    public avro.proto.TSinfo.Builder clearMeasurement() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public TSinfo build() {
      try {
        TSinfo record = new TSinfo();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.measurement = fieldSetFlags()[1] ? this.measurement : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
