/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.proto;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface tsproto {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"tsproto\",\"namespace\":\"avro.proto\",\"types\":[],\"messages\":{\"setcontrollerinfo\":{\"request\":[{\"name\":\"port\",\"type\":\"int\"},{\"name\":\"address\",\"type\":\"string\"}],\"response\":\"int\"}}}");
  int setcontrollerinfo(int port, java.lang.CharSequence address) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends tsproto {
    public static final org.apache.avro.Protocol PROTOCOL = avro.proto.tsproto.PROTOCOL;
    void setcontrollerinfo(int port, java.lang.CharSequence address, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
  }
}