/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.proto;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface user {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"user\",\"namespace\":\"avro.proto\",\"types\":[{\"type\":\"record\",\"name\":\"Lightinfo\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"status\",\"type\":\"boolean\"}]}],\"messages\":{\"recievelights\":{\"request\":[{\"name\":\"light\",\"type\":\"Lightinfo\"}],\"response\":\"null\"}}}");
  java.lang.Void recievelights(avro.proto.Lightinfo light) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends user {
    public static final org.apache.avro.Protocol PROTOCOL = avro.proto.user.PROTOCOL;
    void recievelights(avro.proto.Lightinfo light, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}